export enum EventTypes {
  ROUTE_CHANGED = 'ROUTE_CHANGED',
  ENTER_FULLSCREEN = 'ENTER_FULLSCREEN',
  EXIT_FULLSCREEN = 'EXIT_FULLSCREEN',
  LOAD_COMPLETE = 'LOAD_COMPLETE',
  SET_PATIENT_PRACTICE = 'SET_PATIENT_PRACTICE',
}
